### ISSUE TITLE
Text a inserir quan comencem el tuit de 1714

### ISSUE THREAD

**Issue by antifeudalista** [alextremp/hashtagsxrep#119]
EL TUIT DE LES 17:14
Sabem que la veritat està del nostre costat i que tenim perduda la batalla mediàtica als mitjans tradicionals, però no estem disposats a regalar als dependentistes la presència a twitter sense combatre. 
Per aquesta raó volem llençar diàriament un Hashtag independentista de protesta. 
A les 17 h cada dia publicarem un hashtag protesta al nostre canal de Telegram i llençarem tuits amb aquest hashtag a les 17:14.
Potser els partits independentistes estan desunits. 
Demostrem amb el nostre exemple que nosaltres no ho estem. 

Només cal estar atents al canal de Télegram a les 5 de la tarda per veure el hashtag i publicar un tuit a les 17:14.

https://t.me/Hashtags1714

**Comment by alextremp** [comment]
Tanco!
