### ISSUE TITLE
Saber si entren a la web des de fora de trams

### ISSUE THREAD

**Issue by loida17** [alextremp/hashtagsxrep#120]
Estaria bé saber si hi ha gent que loga directament des de Twitter o des de la publicitat que es fa amb Facebook o la que es farà a Instagram, és a dir gent que faci servir la web però que no estigui a cap tram.

**Comment by alextremp** [comment]
Per fer-ho fàcil podríem disposar de botons de compartir directament a la web, però farà falta dedicar-hi unes hores, la segueixo aplaçant per més endavant
