### ISSUE TITLE
Consells 

### ISSUE THREAD

**Issue by antifeudalista** [alextremp/hashtagsxrep#123]
Al menú, estaria bé que a part de 
#MONITORITZA
#RÀNQUING
#ENQUESTA
#QUISOM
hi hagués:
#CONSELLS 
On quedés guardat tota la info que en Joan penja (al xat o a difusió, i queda en l'oblit).
Consells sobre com tuitar, o fins i tot consells sobre com reaccionar a les manis, o qualsevol altre tema sobre el que puguem aconsellar la gent.

**Comment by alextremp** [comment]
Quan es pugui, intentaré posar això: https://quilljs.com/
